### PR TITLE
Expose Fondant class globally to allow for overrides as needed in app

### PR DESCRIPTION
**Pull request by jdtornow**
Just a minor change to the architecture to allow `Fondant` to be accessible and extended outside of this file. 

Also, I moved the setup from within a `$(function() {});` to just work if jQuery is defined. This allows it to be accessible in the global scope.

Let me know what you think @philtr 

(Tests were already failing so I haven't touched those.)

### CODE REVIEW

**Comment by philtr** [comment]
Yeah, I'm okay with that. I was just following the pattern of the bootstrap jQuery plugins, but I don't have any strong opinions if you feel this change is necessary. I will get this merged in tonight.

The tests pass for me. I think they might be failing for you because I don't include the compiled js in the repo. I will change that to remove friction to get them passing. If you have time and feel like it, can you run `coffee --watch --compile src/**/*.coffee spec/**/*.coffee` and try running the tests again and possibly get them passing? If not, I can do it when I merge. No worries.

**Comment by jdtornow** [comment]
Cool cool. I'm open to other ideas on how to extend it, but we'll definitely want to be able to customize the toolbar per app.

No rush, we can get it tested out shortly.

**Comment by philtr** [comment]
I'd prefer to pass something in to the instantiation function rather than modify the class. Something like this:

``` javascript
$('.rich-text-editor').fondant({
  toolbar: '.custom-toolbar' // selector of toolbar located elsewhere
});
```

or this:

``` javascript
$('.rich-text-editor').fondant({
  toolbar: <%= render 'editor/toolbar' %> // html to insert inside the wrapper
});
```

or if we had to, this:

``` javascript
$('.rich-text-editor').fondant({
  toolbar: {
    bold: '.btn-bold',
    italic: '.btn-italic'
    // ... etc.
  }
});
```

What do you think about that? Would something like that give you the flexibility that you need? **I'm curious to know exactly what you're trying to do so I could make it easy to extend without monkey patching.**

**Comment by jdtornow** [comment]
If we could make it so we can override the template for the toolbar that's what I'm looking for. 

I just need to be able to override this:

https://github.com/ovenbits-ingredients/fondant/blob/master/src/fondant.coffee#L391-L418

**Comment by jdtornow** [comment]
Ok I've tweaked this a bit. Is this more to your liking?

Instead of patching directly in the class, you can now use the `$.fn.fondant.defaults.toolbar` as a function. As long as that function returns a string it'll be used for the toolbar content. It still accepts true/false to show/hide the toolbar but now also accepts a function.

Then, in an app you can do something like this:

``` coffeescript

cmsToolbar = ->
  group = @toolbarClass() + '-button-group'
  button = @toolbarClass() + '-button'
  """
  <div class="cms-fondant-toolbar">
    <a class="toolbar-item" href="#" data-action="#{ @fondant.type }-bold"><i class="icon icon-bold"></i></a>
  </div>
  """

$ ->
  $.fn.fondant.defaults.toolbar = cmsToolbar
```

It still doesn't feel correct to me to have to wait until page load to set the defaults, and I'd rather be able to just set `$.fn.fondant.defaults` outside of the document ready function, but if that's the way these things go then I'll deal with it.

**Comment by courtsimas** [comment]
I feel like this is almost being over engineered. If it works for the user,
then we can tweak further later to be more developer friendly. FWIW... i
kind of like pip's idea better :) but then again, WHOAMI. Just some layman.

**Comment by philtr** [comment]
I think I've got a solution. I'll push it up in a little bit. When I'm not driving. :grin:

**Pull request closed without merging**
